 # -*- coding: utf-8 -*-
"""proyecto_procesamiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KF0LvEXaY-p9bVpYqVlAkVhqo5YcFirP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# --- Importar datos ---
# Leer archivo Excel
df = pd.read_excel("temperaturas_ordenadas.xlsx")

# Crear los arreglos
x = np.arange(len(df))  # índice de cada fila
y = df["temperature_2m"].values  # valores de la columna 'temperature_2m'

# Tamaño de los datos
n = len(x)


# --- REGRESIÓN LINEAL ---
sum_x = np.sum(x)
sum_y = np.sum(y)
sum_xy = np.sum(x * y)
sum_x2 = np.sum(x**2)

b = (n*sum_xy - sum_x*sum_y) / (n*sum_x2 - sum_x**2)
a = (sum_y - b*sum_x) / n

y_pred_lineal = a + b*x

print(f"Recta de regresión lineal: y = {a:.3f} + {b:.3f}x")

# --- REGRESIÓN POLINOMIAL (grado 2) ---
sum_x3 = np.sum(x**3)
sum_x4 = np.sum(x**4)
sum_x2y = np.sum(x**2 * y)

A = np.array([[n, sum_x, sum_x2],
              [sum_x, sum_x2, sum_x3],
              [sum_x2, sum_x3, sum_x4]])
B = np.array([sum_y, sum_xy, sum_x2y])

a2, b2, c2 = np.linalg.solve(A, B)
y_pred_poly = a2 + b2*x + c2*(x**2)

print(f"Ecuación polinomial: y = {a2:.3f} + {b2:.3f}x + {c2:.3f}x²")

# --- GRAFICAR ---
plt.figure(figsize=(10, 6))
plt.scatter(x, y, color='black', label='Datos reales', s=50)
plt.plot(x, y_pred_lineal, color='blue', label='Regresión lineal')
plt.plot(x, y_pred_poly, color='red', linestyle='--', label='Regresión polinomial (grado 2)')
plt.title("Regresión de temperatura respecto al tiempo (Cartagena)")
plt.xlabel("Tiempo (horas)")
plt.ylabel("Temperatura (°C)")
plt.legend()
plt.grid(True)
plt.show()